name: Publish package to GitHub Packages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.12.41
