name: Maven Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Configure git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Verify files and pathing
      run: pwd && ls

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -s settings-github.xml release:clean release:prepare release:perform
