name: Maven Release

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.CICD_TOKEN }}
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      env:
        JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
      with:
        release-branch-name: "main"
        git-release-bot-name: "GitHub Actions"
        git-release-bot-email: "actions@github.com"
        access-token: ${{ secrets.CICD_TOKEN }}
        maven-repo-server-id: github
        maven-repo-server-username: jdwillmsen
        maven-repo-server-password: ${{ secrets.CICD_PASSWORD }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        docker-registry-id: registry.hub.docker.com
        docker-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
        docker-registry-password: ${{ secrets.DOCKER_HUB_PASSWORD }}