name: Maven Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: View settings.xml
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        cat $GITHUB_WORKSPACE/settings.xml

    - name: Configure git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -s $GITHUB_WORKSPACE/settings.xml release:clean release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ github.token }}
