name: Maven Release

on: push

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.CICD_TOKEN }}
    - name: Release
      uses: mg-smartrent/github-actions-maven-release@1.5
      with:
        release-branch-name: "main"
        git-release-bot-name: "GitHub Actions"
        git-release-bot-email: "actions@github.com"
        access-token: ${{ secrets.CICD_TOKEN }}
        maven-repo-server-id: github
        maven-repo-server-username: jdwillmsen
        maven-repo-server-password: ${{ secrets.CICD_PASSWORD }}