name: Maven Release

on: push

permissions:
  packages: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Configure git author
        run: |
          git config --global user.email "jdwillmsen@gmail.com"
          git config --global user.name "Jake Willmsen"
      - name: Publish package
        run: mvn -B release:clean release:prepare release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}