name: Maven Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.CICD_TOKEN }}
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -X -B -s settings-github.xml release:clean release:prepare release:perform
